const accountCards = [
  {
    name: "Razor Sharp",
    type: "Standard Account",
    platform: "MT4 & MT5",
    markets: "All instruments",
    minDeposit: "USD 10",
    bonus: "Yes",
    leverage: "Up to 1:500",
    miniTradeSize: "1.3 pips",
    commission: "No commission",
    swapFees: "No",
    marginCall: "50%",
    stopOut: "30%",
    accountBaseCurrencies: ["ZAR", "USD", "GBP", "EUR"],
    orderExecution: "Market Execution",
    buttonText: "Sign Up"
  },
  {
    name: "Razor Blade",
    type: "VIP Account",
    platform: "MT4 & MT5",
    markets: "All instruments",
    minDeposit: "USD 10",
    bonus: "Yes",
    leverage: "Up to 1:500",
    miniTradeSize: "1.3 pips",
    commission: "No commission",
    swapFees: "No",
    marginCall: "50%",
    stopOut: "30%",
    accountBaseCurrencies: ["ZAR", "USD", "GBP", "EUR"],
    orderExecution: "Market Execution",
    buttonText: "Sign Up"
  },
  {
    name: "Razor Edge",
    type: "Micro Account",
    platform: "MT4 & MT5",
    markets: "All instruments",
    minDeposit: "USD 10",
    bonus: "Yes",
    leverage: "Up to 1:500",
    miniTradeSize: "1.3 pips",
    commission: "No commission",
    swapFees: "No",
    marginCall: "50%",
    stopOut: "30%",
    accountBaseCurrencies: ["ZAR", "USD", "GBP", "EUR"],
    orderExecution: "Market Execution",
    buttonText: "Sign Up"
  }
];
